aws:
  region: gra
  bucket: quantalogic-bucket
  credentials:
    accessKeyId: f877fd7af7434cdc83add470723bd098
    secretAccessKey: 9778d5a15f9443bf825f6e2ff6a242ce
  endpoint: https://s3.gra.io.cloud.ovh.net/

upload:
  destinationFolder: /temp
  sourceFolder: ./uploads
  maxFileSizeMB: 100
  retryAttempts: 3
download:
  sourceFolder: /temp
  destinationFolder: ./downloads
  retryAttempts: 3
  skipExisting: False
